qb = [
  {Team: "Arizona Cardinals", Quarterback: "Kyler Murray", Weight: 207, Height: "5'10\"", passingYards: 162, Completions: 21, Attempts: 31},
  {Team: "Alanta Falcons", Quarterback: "Kirk Cousins", Weight: 205, Height: "6'3\"", passingYards: 155, Completions: 16, Attempts: 26},
  {Team: "Baltimore Ravens", Quarterback: "Lamar Jackson", Weight: 205, Height: "6'2\"", passingYards: 273, Completions: 26, Attempts: 41},
  {Team: "Buffalo Bills", Quarterback: "Josh Allen", Weight: 237, Height: "6'5\"", passingYards: 232, Completions: 18, Attempts: 23},
  {Team: "Carolina Panthers", Quarterback: "Bryce Young", Weight: 204, Height: "5'10\"", passingYards: 161, Completions: 13, Attempts: 30},
  {Team: "Chicago Bears", Quarterback: "Caleb Williams", Weight: 215, Height: "6'1\"", passingYards: 93, Completions: 14, Attempts: 29},
  {Team: "Cincinnati Bengals", Quarterback: "Joe Burrow", Weight: 215, Height: "6'4\"", passingYards: 164, Completions: 21, Attempts: 29},
  {Team: "Cleveland Browns", Quarterback: "Deshaun Watson", Weight: 223, Height: "6'2\"", passingYards: 169, Completions: 24, Attempts: 45},
  {Team: "Dallas Cowboys", Quarterback: "Dak Prescott", Weight: 238, Height: "6'2\"", passingYards: 179, Completions:19, Attempts: 32},
  {Team: "Denver Broncos", Quarterback: "Bo Nix", Weight: 217, Height: "6'2\"", passingYards: 138, Completions: 26, Attempts: 42},
  {Team: "Detroit Lions", Quarterback: "Jared Goff", Weight: 217, Height: "6'4\"", passingYards: 217, Completions: 18, Attempts: 28},
  {Team: "Green Bay Packers", Quarterback: "Jordan Love", Weight: 219, Height: "6'4\"", passingYards: 260, Completions: 17, Attempts: 34},
  {Team: "Houston Texans", Quarterback: "C.J. Stroud", Weight: 218, Height: "6'3\"", passingYards: 234, Completions: 24, Attempts: 32},
  {Team: "Indianapolis Colts", Quarterback: "Anthony Richardson", Weight: 244, Height: "6'4\"", passingYards: 212, Completions: 9, Attempts: 19},
  {Team: "Jacksonville Jaguars", Quarterback: "Trvor Lawrence", Weight: 220, Height: "6'6\"", passingYards: 162, Completions: 12, Attempts: 21},
  {Team: "Kansas City Chiefs", Quarterback: "Patrick Mahomes", Weight: 225, Height: "6'2\"", passingYards: 291, Completions: 20, Attempts: 28},
  {Team: "Las Vegas Raiders", Quarterback: "Gardner Minshew", Weight: 225, Height: "6'1\"", passingYards: 257, Completions: 25, Attempts: 33},
  {Team: "Los Angeles Chargers", Quarterback: "Justin Herbert", Weight: 236, Height: "6'6\"", passingYards: 144, Completions: 17, Attempts: 26},
  {Team: "Los Angeles Rams", Quarterback: "Matthew Stafford", Weight: 214, Height: "6'3\"", passingYards: 317, Completions: 34, Attempts: 49},
  {Team: "Miami Dolphins", Quarterback: "Tua Tagovailoa", Weight: 225, Height: "6'1\"", passingYards: 338, Completions: 23, Attempts: 37},
  {Team: "Minnesota Vikings", Quarterback: "Sam Darnold", Weight: 225, Height: "6'3\"", passingYards: 208, Completions: 19, Attempts: 24},
  {Team: "New England Patriots", Quarterback: "Jacoby Brissett", Weight: 235, Height: "6'4\"", passingYards: 121, Completions: 15, Attempts: 24},
  {Team: "New Orleans Saints", Quarterback: "Derek Carr", Weight: 215, Height: "6'3\"", passingYards: 200, Completions: 19, Attempts: 23},
  {Team: "New York Giants", Quarterback: "Daniel Jones", Weight: 230, Height: "6'5\"", passingYards: 186, Completions: 22, Attempts: 42},
  {Team: "New York Jets", Quarterback: "Aaron Rodgers", Weight: 223, Height: "6'2\"", passingYards: 167, Completions: 13, Attempts: 21},
  {Team: "Philadelphia Eagles", Quarterback: "Jalen Hurts", Weight: 223, Height: "6'1\"", passingYards: 278, Completions: 20, Attempts: 34},
  {Team: "Pittsburgh Steelers", Quarterback: "Justin Fields", Weight: 227, Height: "6'3\"", passingYards: 156, Completions: 17, Attempts: 23},
  {Team: "San Francisco 49ers", Quarterback: "Brock Purdy", Weight: 220, Height: "6'1\"", passingYards: 231, Completions: 19, Attempts: 29},
  {Team: "Seattle Seahawks", Quarterback: "Geno Smith", Weight: 221, Height: "6'3\"", passingYards: 171, Completions: 18, Attempts: 25},
  {Team: "Tampa Bay Buccaneers", Quarterback: "Baker Mayfield", Weight: 215, Height: "6'1\"", passingYards: 289, Completions: 24, Attempts: 30},
  {Team: "Tennessee Titans", Quarterback: "Will Levis", Weight: 229, Height: "6'4\"", passingYards: 127, Completions: 19, Attempts: 32},
  {Team: "Washington Commanders", Quarterback: "Jayden Daniels", Weight: 210, Height: "6'4\"", passingYards: 184, Completions: 17, Attempts: 24}
  ]
