wr = [
  {Team: "Arizona Cardinals", Widereceiver: "Greg Dortch", Weight: 175, Height: "5' 7\"", receivingYards: 47, Receptions: 6, Targetedreceiver: 8},
  {Team: "Alanta Falcons", Widereceiver: "Drake London", Weight: 213, Height: "6' 4\"", receivingYards: 15, Receptions: 2, Targetedreceiver: 3},
  {Team: "Baltimore Ravens", Widereceiver: "Zay Flowers", Weight: 175, Height: "5' 9\"", receivingYards: 37, Receptions: 6, Targetedreceiver: 10},
  {Team: "Buffalo Bills", Widereceiver: "Khalil Shakir", Weight: 190, Height: "6' 0\"", receivingYards: 42, Receptions: 3, Targetedreceiver: 3},
  {Team: "Carolina Panthers", Widereceiver: "Adam Thielen", Weight: 195, Height: "6' 2\"", receivingYards: 49, Receptions: 3, Targetedreceiver: 4},
  {Team: "Chicago Bears", Widereceiver: "DJ Moore", Weight: 210, Height: "6' 0\"", receivingYards: 36, Receptions: 5, Targetedreceiver: 8},
  {Team: "Cincinnati Bengals", Widereceiver: "Ja'Marr Chase", Weight: 205, Height: "6' 0\"", receivingYards: 62, Receptions: 6, Targetedreceiver: 6},
  {Team: "Cleveland Browns", Widereceiver: "Elijah Moore", Weight: 180, Height: "5' 10\"", receivingYards: 9, Receptions: 3, Targetedreceiver: 6},
  {Team: "Dallas Cowboys", Widereceiver: "CeeDee Lamb", Weight: 200, Height: "6' 2\"", receivingYards: 61, Receptions: 5, Targetedreceiver: 10},
  {Team: "Denver Broncos", Widereceiver: "Devaughn Vale", Weight: 210, Height: "6' 5\"", receivingYards: 39, Receptions: 8, Targetedreceiver: 8},
  {Team: "Detroit Lions", Widereceiver: "Jameson Williams", Weight: 180, Height: "6' 1\"", receivingYards: 121, Receptions: 5, Targetedreceiver: 9},
  {Team: "Green Bay Packers", Widereceiver: "Jayden Reed", Weight: 187, Height: "5' 11\"", receivingYards: 138, Receptions: 4, Targetedreceiver: 6},
  {Team: "Houston Texans", Widereceiver: "Nico Collins", Weight: 191, Height: "6' 0\"", receivingYards: 117, Receptions: 6, Targetedreceiver: 8},
  {Team: "Indianapolis Colts", Widereceiver: "Alec Pierce", Weight: 211, Height: "6' 3\"", receivingYards: 125, Receptions: 3, Targetedreceiver: 3},
  {Team: "Jacksonville Jaguars", Widereceiver: "Brian Thomas Jr.", Weight: 209, Height: "6' 2\"", receivingYards: 47, Receptions: 4, Targetedreceiver: 4},
  {Team: "Kansas City Chiefs", Widereceiver: "Rashee Rice", Weight: 205, Height: "6' 2\"", receivingYards: 103, Receptions: 7, Targetedreceiver: 9},
  {Team: "Las Vegas Raiders", Widereceiver: "Jakobi Meyers", Weight: 200, Height: "6' 2\"", receivingYards: 61, Receptions: 3, Targetedreceiver: 3},
  {Team: "Los Angeles Chargers", Widereceiver: "Quentin Johnston", Weight: 215, Height: "6' 4\"", receivingYards: 38, Receptions: 3, Targetedreceiver: 5},
  {Team: "Los Angeles Rams", Widereceiver: "Cooper Kupp", Weight: 208, Height: "6' 2\"", receivingYards: 110, Receptions: 14, Targetedreceiver: 21},
  {Team: "Miami Dolphins", Widereceiver: "Tyreek Hill", Weight: 191, Height: "5' 9\"", receivingYards: 130, Receptions: 7, Targetedreceiver: 12},
  {Team: "Minnesota Vikings", Widereceiver: "Justin Jefferson", Weight: 195, Height: "6' 1\"", receivingYards: 59, Receptions: 4, Targetedreceiver: 6},
  {Team: "New England Patriots", Widereceiver: "K.J. Osborn", Weight: 200, Height: "6' 0\"", receivingYards: 21, Receptions: 3, Targetedreceiver: 6},
  {Team: "New Orleans Saints", Widereceiver: "Rashid Shaheed", Weight: 181, Height: "6' 0\"", receivingYards: 73, Receptions: 3, Targetedreceiver: 5},
  {Team: "New York Giants", Widereceiver: "Malik Nabers", Weight: 200, Height: "6' 0\"", receivingYards: 66, Receptions: 5, Targetedreceiver: 6},
  {Team: "New York Jets", Widereceiver: "Garrett Wilson", Weight: 183, Height: "6' 0\"", receivingYards: 60, Receptions: 6, Targetedreceiver: 11},
  {Team: "Philadelphia Eagles", Widereceiver: "A.J. Brown", Weight: 226, Height: "6' 1\"", receivingYards: 119, Receptions: 5, Targetedreceiver: 10},
  {Team: "Pittsburgh Steelers", Widereceiver: "George Pickens", Weight: 200, Height: "6' 3\"", receivingYards: 85, Receptions: 6, Targetedreceiver: 7},
  {Team: "San Francisco 49ers", Widereceiver: "Jauan Jennings", Weight: 212, Height: "6' 3\"", receivingYards: 64, Receptions: 5, Targetedreceiver: 5},
  {Team: "Seattle Seahawks", Widereceiver: "Tyler Lockett", Weight: 182, Height: "5' 10\"", receivingYards: 77, Receptions: 6, Targetedreceiver: 7},
  {Team: "Tampa Bay Buccaneers", Widereceiver: "Chris Godwin", Weight: 209, Height: "6' 1\"", receivingYards: 83, Receptions: 8, Targetedreceiver: 8},
  {Team: "Tennessee Titans", Widereceiver: "Calvin Ridley", Weight: 190, Height: "6' 1\"", receivingYards: 50, Receptions: 3, Targetedreceiver: 7},
  {Team: "Washington Commanders", Widereceiver: "Luke McCaffrey", Weight: 198, Height: "6' 2\"", receivingYards: 18, Receptions: 3, Targetedreceiver: 3}
  
]
